/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package coin.conversion;

import java.util.Scanner;

import resources.CurrencyConverter;

public class App {

    public static void main(String[] args) {
        Scanner readScanner = new Scanner(System.in);
        int optionMenu = 0;

        while (optionMenu != 7) {
            System.out.println("*************************************************");
            System.out.println("Seja bem-vindo/a ao Conversor de Moeda =)\r\n" + //
                    "1) Dólar =>> Peso argentino\r\n" + //
                    "2) Peso argentino =>> Dólar\r\n" + //
                    "3) Dólar =>> Real brasileiro\r\n" + //
                    "4) Real brasileiro =>> Dólar\r\n" + //
                    "5) Dólar =>>> Peso colombiano\r\n" + //
                    "6) Peso colombiano =>> Dólar\r\n" + //
                    "7) Sair\r\n" + //
                    "Escolha uma opção válida:");
            System.out.println("*************************************************");
            optionMenu = readScanner.nextInt();

            CurrencyConverter converter = new CurrencyConverter();
            double valueConvert;
            double conversationResult;

            switch (optionMenu) {
                case 1:
                    System.out.println("Digite um valor");
                    valueConvert = readScanner.nextDouble();
                    conversationResult = converter.convertUSDToBRL(valueConvert, "USD", "ARS");
                    System.out.println("conversationResult: " + conversationResult);
                    break;
                case 2:
                    System.out.println("Digite um valor");
                    valueConvert = readScanner.nextDouble();
                    conversationResult = converter.convertUSDToBRL(valueConvert, "ARS", "USD");
                    System.out.println("conversationResult: " + conversationResult);
                    break;
                case 3:
                    System.out.println("Digite um valor");
                    valueConvert = readScanner.nextDouble();
                    conversationResult = converter.convertUSDToBRL(valueConvert, "USD", "BRL");
                    System.out.println("conversationResult: " + conversationResult);
                    break;
                case 4:
                    System.out.println("Digite um valor");
                    valueConvert = readScanner.nextDouble();
                    conversationResult = converter.convertUSDToBRL(valueConvert, "BRL", "USD");
                    System.out.println("conversationResult: " + conversationResult);
                    break;
                case 5:
                    System.out.println("Digite um valor");
                    valueConvert = readScanner.nextDouble();
                    conversationResult = converter.convertUSDToBRL(valueConvert, "USD", "COP");
                    System.out.println("conversationResult: " + conversationResult);
                    break;
                case 6:
                    System.out.println("Digite um valor");
                    valueConvert = readScanner.nextDouble();
                    conversationResult = converter.convertUSDToBRL(valueConvert, "COP", "USD");
                    System.out.println("conversationResult: " + conversationResult);
                    break;
                default:
                    break;
            }
        }
    }
}
